name: Sync to JohnDev404

on:
  push:
    branches:
      - main
      - master


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to JohnDev404
        env:
          TOKEN: ${{ secrets.JOHNDEV404_TOKEN }}
        run: |
          git config --global user.name "john-andeyyy"
          git config --global user.email "andreinicolas.codebank@gmail.com"
          git remote add johnDev404 https://$TOKEN@github.com/JohnDev404/Quiz-Api.git
          git push johnDev404 main --force
